// packages/base-ui/docs-solid/src/demos/solid/handbook/forms/components/autocomplete.tsx
import { splitProps } from 'solid-js';
import clsx from 'clsx';
import { Autocomplete } from '@solidports/base-ui/autocomplete';

export function Root(props: Autocomplete.Root.Props<any>) {
  return <Autocomplete.Root {...props} />;
}

export function Input(props: Autocomplete.Input.Props) {
  const [local, others] = splitProps(props, ['class']);
  return (
    <Autocomplete.Input
      class={clsx(
        'bg-[canvas] h-10 w-[16rem] md:w-[20rem] font-normal rounded-md border border-gray-200 pl-3.5 text-base text-gray-900 focus:outline focus:outline-2 focus:-outline-offset-1 focus:outline-blue-800',
        local.class,
      )}
      {...others}
    />
  );
}

export function Portal(props: Autocomplete.Portal.Props) {
  return <Autocomplete.Portal {...props} />;
}

export function Positioner(props: Autocomplete.Positioner.Props) {
  const [local, others] = splitProps(props, ['class']);
  return (
    <Autocomplete.Positioner
      class={clsx('outline-none data-[empty]:hidden', local.class)}
      sideOffset={4}
      {...others}
    />
  );
}

export function Popup(props: Autocomplete.Popup.Props) {
  const [local, others] = splitProps(props, ['class']);
  return (
    <Autocomplete.Popup
      class={clsx(
        'w-[var(--anchor-width)] max-h-[min(var(--available-height),23rem)] max-w-[var(--available-width)] overflow-y-auto scroll-pt-2 scroll-pb-2 overscroll-contain rounded-md bg-[canvas] py-2 text-gray-900 shadow-lg shadow-gray-200 outline-1 outline-gray-200 dark:shadow-none dark:-outline-offset-1 dark:outline-gray-300',
        local.class,
      )}
      {...others}
    />
  );
}

export function List(props: Autocomplete.List.Props) {
  return <Autocomplete.List {...props} />;
}

export function Item(props: Autocomplete.Item.Props) {
  const [local, others] = splitProps(props, ['class']);
  return (
    <Autocomplete.Item
      class={clsx(
        'flex flex-col gap-0.25 cursor-default py-2 pr-8 pl-4 text-base leading-4 outline-none select-none data-[highlighted]:relative data-[highlighted]:z-0 data-[highlighted]:text-gray-50 data-[highlighted]:before:absolute data-[highlighted]:before:inset-x-2 data-[highlighted]:before:inset-y-0 data-[highlighted]:before:z-[-1] data-[highlighted]:before:rounded data-[highlighted]:before:bg-gray-900',
        local.class,
      )}
      {...others}
    />
  );
}

// packages/base-ui/docs/solid/src/demos/solid/handbook/forms/components/autocomplete.tsx
const React = { forwardRef: (render) => (props) => render(props, props.ref), useActionState: (_action, initial) => [initial, () => {}, false] };

import clsx from 'clsx';
import { Autocomplete } from '@solidports/base-ui/autocomplete';

export function Root(props: Autocomplete.Root.Props<any>) {
  return <Autocomplete.Root {...props} />;
}

export const Input = React.forwardRef<HTMLInputElement, Autocomplete.Input.Props>(function Input(
  { className, ...props }: Autocomplete.Input.Props,
  forwardedRef: React.ForwardedRef<HTMLInputElement>,
) {
  return (
    <Autocomplete.Input
      ref={forwardedRef}
      class={clsx(
        'h-8 w-[16rem] border border-neutral-950 bg-white px-2 text-sm any-pointer-coarse:text-base font-normal text-neutral-950 placeholder:text-neutral-500 focus:outline-2 focus:-outline-offset-1 focus:outline-neutral-950 dark:focus:outline-white md:w-[20rem] dark:border-white dark:bg-neutral-950 dark:text-white dark:placeholder:text-neutral-400',
        className,
      )}
      {...props}
    />
  );
});

export function Portal(props: Autocomplete.Portal.Props) {
  return <Autocomplete.Portal {...props} />;
}

export function Positioner({ className, ...props }: Autocomplete.Positioner.Props) {
  return (
    <Autocomplete.Positioner
      class={clsx('outline-none data-empty:hidden', className)}
      sideOffset={4}
      {...props}
    />
  );
}

export function Popup({ className, ...props }: Autocomplete.Popup.Props) {
  return (
    <Autocomplete.Popup
      class={clsx(
        'w-(--anchor-width) max-w-(--available-width) border border-neutral-950 bg-white text-neutral-950 shadow-[0.25rem_0.25rem_0] shadow-black/12 dark:border-white dark:bg-neutral-950 dark:text-white dark:shadow-none',
        className,
      )}
      {...props}
    />
  );
}

export function List({ className, ...props }: Autocomplete.List.Props) {
  return (
    <Autocomplete.List
      class={clsx(
        'max-h-[min(22.5rem,var(--available-height))] overflow-y-auto overscroll-contain py-1 scroll-py-1 outline-0 data-empty:p-0',
        className,
      )}
      {...props}
    />
  );
}

export function Item({ className, ...props }: Autocomplete.Item.Props) {
  return (
    <Autocomplete.Item
      class={clsx(
        'flex cursor-default flex-col gap-0.25 py-2 pr-8 pl-2 text-sm leading-4 outline-none select-none data-highlighted:relative data-highlighted:z-0 data-highlighted:text-white data-highlighted:before:absolute data-highlighted:before:inset-0 data-highlighted:before:z-[-1] data-highlighted:before:bg-neutral-950 dark:data-highlighted:text-neutral-950 dark:data-highlighted:before:bg-white',
        className,
      )}
      {...props}
    />
  );
}
